//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxService.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaxService.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to relationships under state law).
        /// </summary>
        public static string adda4 {
            get {
                return ResourceManager.GetString("adda4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Doc Files.
        /// </summary>
        public static string Additional_doc_files {
            get {
                return ResourceManager.GetString("Additional_doc_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information and Questions Related to the Preparation of Your Return.
        /// </summary>
        public static string Additional_information_and_question_related {
            get {
                return ResourceManager.GetString("Additional_information_and_question_related", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopt a child?.
        /// </summary>
        public static string Adopt_a_child {
            get {
                return ResourceManager.GetString("Adopt_a_child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimony income or separate maintenance payments?.
        /// </summary>
        public static string Alimony_income_or_seprate_maintenence_payments {
            get {
                return ResourceManager.GetString("Alimony_income_or_seprate_maintenence_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alimony or separate maintenance payments? If yes, do you have the recipient’s SSN?.
        /// </summary>
        public static string Alimony_or_seprate_maintenance_payments_if {
            get {
                return ResourceManager.GetString("Alimony_or_seprate_maintenance_payments_if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any of the following?.
        /// </summary>
        public static string Any_of_the_following {
            get {
                return ResourceManager.GetString("Any_of_the_following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to anyone.
        /// </summary>
        public static string Anyone {
            get {
                return ResourceManager.GetString("Anyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apt #.
        /// </summary>
        public static string Apt {
            get {
                return ResourceManager.GetString("Apt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a U.S. citizen?.
        /// </summary>
        public static string Are_you_a_us_citizen {
            get {
                return ResourceManager.GetString("Are_you_a_us_citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of December 31, 2020, what was your marital status?.
        /// </summary>
        public static string As_of_december_thirtyfirst {
            get {
                return ResourceManager.GetString("As_of_december_thirtyfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.I..
        /// </summary>
        public static string as4 {
            get {
                return ResourceManager.GetString("as4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string as5 {
            get {
                return ResourceManager.GetString("as5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime telephone number.
        /// </summary>
        public static string as6 {
            get {
                return ResourceManager.GetString("as6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string as8 {
            get {
                return ResourceManager.GetString("as8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string as9 {
            get {
                return ResourceManager.GetString("as9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally and permanently disabled.
        /// </summary>
        public static string asdf4 {
            get {
                return ResourceManager.GetString("asdf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-time student.
        /// </summary>
        public static string asdf5 {
            get {
                return ResourceManager.GetString("asdf5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legally blind.
        /// </summary>
        public static string asdf6 {
            get {
                return ResourceManager.GetString("asdf6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUNT.
        /// </summary>
        public static string AUNT {
            get {
                return ResourceManager.GetString("AUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Number 52121E.
        /// </summary>
        public static string az7 {
            get {
                return ResourceManager.GetString("az7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.irs.gov.
        /// </summary>
        public static string az8 {
            get {
                return ResourceManager.GetString("az8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form 13614-C (Rev. 10-2020).
        /// </summary>
        public static string az9 {
            get {
                return ResourceManager.GetString("az9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROTHER.
        /// </summary>
        public static string BROTHER {
            get {
                return ResourceManager.GetString("BROTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can anyone claim you or your spouse as a dependent?.
        /// </summary>
        public static string Can_anyone_claim_you_or_your {
            get {
                return ResourceManager.GetString("Can_anyone_claim_you_or_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash/check/virtual currency payments, or other property or services for any work performed not reported on Forms W-2 or 1099?.
        /// </summary>
        public static string Cash_check_virtual_currency_payments {
            get {
                return ResourceManager.GetString("Cash_check_virtual_currency_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charitable Contributions.
        /// </summary>
        public static string Charitable_contributions {
            get {
                return ResourceManager.GetString("Charitable_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check here if you, or your spouse if filing jointly, want $3 to go to this fund.
        /// </summary>
        public static string Chech_here_if_you_or_your_spouse_if {
            get {
                return ResourceManager.GetString("Chech_here_if_you_or_your_spouse_if", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check appropriate box for each question in each section.
        /// </summary>
        public static string Check_appropriate_box_for_each_question_in_each {
            get {
                return ResourceManager.GetString("Check_appropriate_box_for_each_question_in_each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child or dependent care expenses such as daycare?.
        /// </summary>
        public static string Child_or_dependent_care_expences {
            get {
                return ResourceManager.GetString("Child_or_dependent_care_expences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your File.
        /// </summary>
        public static string Choose_your_file {
            get {
                return ResourceManager.GetString("Choose_your_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College or post secondary educational expenses for yourself, spouse or dependents? (Form 1098-T).
        /// </summary>
        public static string College_or_post_secondry_education {
            get {
                return ResourceManager.GetString("College_or_post_secondry_education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Complete the Form Below.
        /// </summary>
        public static string completeformbelow {
            get {
                return ResourceManager.GetString("completeformbelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent:.
        /// </summary>
        public static string Consent {
            get {
                return ResourceManager.GetString("Consent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions to a retirement account?.
        /// </summary>
        public static string Contribution_to_a_retirement_account {
            get {
                return ResourceManager.GetString("Contribution_to_a_retirement_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (mm/dd/yy).
        /// </summary>
        public static string Date_format {
            get {
                return ResourceManager.GetString("Date_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string Date_of_births {
            get {
                return ResourceManager.GetString("Date_of_births", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of final decree.
        /// </summary>
        public static string Date_of_final_decree {
            get {
                return ResourceManager.GetString("Date_of_final_decree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of separate maintenance decre.
        /// </summary>
        public static string Date_of_separate_maintenance_decre {
            get {
                return ResourceManager.GetString("Date_of_separate_maintenance_decre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAUGHTER.
        /// </summary>
        public static string DAUGHTER {
            get {
                return ResourceManager.GetString("DAUGHTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daytime telephone number.
        /// </summary>
        public static string Daytime_telephone_number {
            get {
                return ResourceManager.GetString("Daytime_telephone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (b).
        /// </summary>
        public static string dc3 {
            get {
                return ResourceManager.GetString("dc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (c).
        /// </summary>
        public static string dc5 {
            get {
                return ResourceManager.GetString("dc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of the Treasury - Internal Revenue Service.
        /// </summary>
        public static string DeptName {
            get {
                return ResourceManager.GetString("DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did the  taxpayer(s)  pay more than half the cost of maintaining a home for this person? (yes/no).
        /// </summary>
        public static string Did_the_taxpayers_pay_more_than_half_the_cost {
            get {
                return ResourceManager.GetString("Did_the_taxpayers_pay_more_than_half_the_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did the taxpayer(s) provide more  than 50% of support for  this person? (yes/no/n/a).
        /// </summary>
        public static string Did_the_taxpayers_provide_more_than_fiftypercent {
            get {
                return ResourceManager.GetString("Did_the_taxpayers_provide_more_than_fiftypercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did this person have less than $4,300 of income? (yes,no,n/a).
        /// </summary>
        public static string Did_this_person_have_less_than_fortythree {
            get {
                return ResourceManager.GetString("Did_this_person_have_less_than_fortythree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did this person  provide more than 50% of his/ her own support? (yes,no,n/a).
        /// </summary>
        public static string Did_this_person_provide_more_than_fifty {
            get {
                return ResourceManager.GetString("Did_this_person_provide_more_than_fifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you live in an area that was declared a Federal disaster area?.
        /// </summary>
        public static string Did_you_live_in_an_area_that {
            get {
                return ResourceManager.GetString("Did_you_live_in_an_area_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you live with your spouse during any part of the last six months of 2020?.
        /// </summary>
        public static string Did_you_live_with_your_spouse_during_any {
            get {
                return ResourceManager.GetString("Did_you_live_with_your_spouse_during_any", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you, or your spouse if filing jointly, receive a letter from the IRS?.
        /// </summary>
        public static string Did_you_or_your_spouse_if_filling_jointly {
            get {
                return ResourceManager.GetString("Did_you_or_your_spouse_if_filling_jointly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct deposit.
        /// </summary>
        public static string Direct_deposite {
            get {
                return ResourceManager.GetString("Direct_deposite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability income? (such as payments from insurance, or workers compensation) (Forms 1099-R, W-2).
        /// </summary>
        public static string Disability_income_such {
            get {
                return ResourceManager.GetString("Disability_income_such", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        public static string Divorced {
            get {
                return ResourceManager.GetString("Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form 13614-C (Rev. 10-2020).
        /// </summary>
        public static string ed1 {
            get {
                return ResourceManager.GetString("ed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have questions, please ask the IRS-certified volunteer preparer..
        /// </summary>
        public static string engl1 {
            get {
                return ResourceManager.GetString("engl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteers are trained to provide high quality service and uphold the highest ethical standards.
        ///To report unethical behavior to the IRS, email us at.
        /// </summary>
        public static string engl2 {
            get {
                return ResourceManager.GetString("engl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wi.voltax@irs.gov.
        /// </summary>
        public static string engl3 {
            get {
                return ResourceManager.GetString("engl3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to etc.).
        /// </summary>
        public static string etc {
            get {
                return ResourceManager.GetString("etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to everyone.
        /// </summary>
        public static string Everyone {
            get {
                return ResourceManager.GetString("Everyone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses related to self-employment income or any other income you received?.
        /// </summary>
        public static string Expences_related_to_self_employment_income {
            get {
                return ResourceManager.GetString("Expences_related_to_self_employment_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File a federal return last year containing a “capital loss carryover” on Form 1040 Schedule D?.
        /// </summary>
        public static string File_a_federal_return_last_year {
            get {
                return ResourceManager.GetString("File_a_federal_return_last_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is Required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For supplies used as an eligible educator such as a teacher, teacher’s aide, counselor, etc.?.
        /// </summary>
        public static string For_supplies_used_as_an_eligible {
            get {
                return ResourceManager.GetString("For_supplies_used_as_an_eligible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        public static string Form {
            get {
                return ResourceManager.GetString("Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13614-C.
        /// </summary>
        public static string Formnum {
            get {
                return ResourceManager.GetString("Formnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (October 2020).
        /// </summary>
        public static string Formocdate {
            get {
                return ResourceManager.GetString("Formocdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOSTER CHILD.
        /// </summary>
        public static string FOSTER_CHILD {
            get {
                return ResourceManager.GetString("FOSTER_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401K.
        /// </summary>
        public static string Fourhundredone_k {
            get {
                return ResourceManager.GetString("Fourhundredone_k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-time student.
        /// </summary>
        public static string Full_time_student {
            get {
                return ResourceManager.GetString("Full_time_student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-time Student last year.
        /// </summary>
        public static string Full_time_student_last_year_yes_or_no {
            get {
                return ResourceManager.GetString("Full_time_student_last_year_yes_or_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsure.
        /// </summary>
        public static string gb10 {
            get {
                return ResourceManager.GetString("gb10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRANDCHILD.
        /// </summary>
        public static string GRANDCHILD {
            get {
                return ResourceManager.GetString("GRANDCHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRANDPARENT.
        /// </summary>
        public static string GRANDPARENT {
            get {
                return ResourceManager.GetString("GRANDPARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HALF BROTHER.
        /// </summary>
        public static string HALF_BROTHER {
            get {
                return ResourceManager.GetString("HALF_BROTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HALF SISTER.
        /// </summary>
        public static string HALF_SISTER {
            get {
                return ResourceManager.GetString("HALF_SISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a Health Savings Account? (Forms 5498-SA, 1099-SA, W-2 with code W in box 12).
        /// </summary>
        public static string Have_a_helth_saving_account {
            get {
                return ResourceManager.GetString("Have_a_helth_saving_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have credit card or mortgage debt cancelled/forgiven by a lender or have a home foreclosure? (Forms 1099-C, 1099-A).
        /// </summary>
        public static string Have_credit_card_or_mortgage_debt {
            get {
                return ResourceManager.GetString("Have_credit_card_or_mortgage_debt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have Earned Income Credit, Child Tax Credit or American Opportunity Credit disallowed in a prior year? If yes, for which tax year?.
        /// </summary>
        public static string Have_earned_income_credit {
            get {
                return ResourceManager.GetString("Have_earned_income_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have health coverage through the Marketplace (Exchange)? [Provide Form 1095-A].
        /// </summary>
        public static string Have_health_coverage_through_the {
            get {
                return ResourceManager.GetString("Have_health_coverage_through_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you, your spouse, or dependents been a victim of tax related identity theft or been issued an Identity Protection PIN?.
        /// </summary>
        public static string Have_you_your_spouse_or_dependents_been_a {
            get {
                return ResourceManager.GetString("Have_you_your_spouse_or_dependents_been_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I authorize my Tax Preparer to enter the five number PIN I have choosen below..
        /// </summary>
        public static string I_authorize_my_tax_prepare_to_enter_the {
            get {
                return ResourceManager.GetString("I_authorize_my_tax_prepare_to_enter_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/we hereby consent to the disclosure of tax return information described in the Global Carry Forward terms above and allow the tax return preparer to enter a PIN in the tax preparation software on my behalf to verify that I/we  consent to the terms of this disclosure..
        /// </summary>
        public static string I_here_by_consent_to_the_disclosure {
            get {
                return ResourceManager.GetString("I_here_by_consent_to_the_disclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I/we, the taxpayer, have read the above information..
        /// </summary>
        public static string I_or_we_the_taxpayers_have_read_the {
            get {
                return ResourceManager.GetString("I_or_we_the_taxpayers_have_read_the", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If additional space is needed check here and list on page 3.
        /// </summary>
        public static string If_additional_space_is_needed_check_here {
            get {
                return ResourceManager.GetString("If_additional_space_is_needed_check_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (If you are filing a joint return, enter your names in the same order as last year’s return).
        /// </summary>
        public static string If_uou_are_filling_a_joint_return {
            get {
                return ResourceManager.GetString("If_uou_are_filling_a_joint_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If Yes, Did you get married in 2020?.
        /// </summary>
        public static string If_yes_did_you_get_married {
            get {
                return ResourceManager.GetString("If_yes_did_you_get_married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If yes, how many jobs did you have last year?.
        /// </summary>
        public static string If_yes_how_many_jobs_did_you_have_last_year {
            get {
                return ResourceManager.GetString("If_yes_how_many_jobs_did_you_have_last_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If yes, where?.
        /// </summary>
        public static string If_yes_where {
            get {
                return ResourceManager.GetString("If_yes_where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are due a refund, would you like:.
        /// </summary>
        public static string If_you_are_due_a_refund {
            get {
                return ResourceManager.GetString("If_you_are_due_a_refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you believe your tax return information has been disclosed or used improperly in a manner unauthorized by law or without your permission, you may contact the Treasury Inspector General for Tax Administration (TIGTA) by telephone at 1-800-366-4484, or by e-mail at complaints@tigta.treas.gov..
        /// </summary>
        public static string If_you_belive_your_tax_return_information {
            get {
                return ResourceManager.GetString("If_you_belive_your_tax_return_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a balance due, would you like to make a payment directly from your bank account?.
        /// </summary>
        public static string If_you_have_a_balance_due {
            get {
                return ResourceManager.GetString("If_you_have_a_balance_due", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not required to complete this form to engage our tax return preparation services. If we obtain your signature on this form by conditioning our tax return preparation services on your consent, your consent will not be valid. If you  agree to the disclosure of your tax return information, your consent is valid for the amount of time that you specify. If  you do not specify the duration of your consent, your consent is valid for one year from the date of signature..
        /// </summary>
        public static string ik1 {
            get {
                return ResourceManager.GetString("ik1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms:.
        /// </summary>
        public static string ik2 {
            get {
                return ResourceManager.GetString("ik2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Carry Forward of data allows TaxSlayer LLC, the provider of the VITA/TCE tax software, to make your tax return information available to ANY volunteer site participating in the IRS&apos;s VITA/TCE program that you select to prepare a tax return in the next filing season. This means you will be able to visit any volunteer site using TaxSlayer next year and have your tax return populate with your current year data, regardless of where you filed your tax return this year. This consent is valid through Novembe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ik3 {
            get {
                return ResourceManager.GetString("ik3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tax return information that will be disclosed includes, but is not limited to, demographic, financial and other personally identifiable information, about you, your tax return and your sources of income, which was input into the tax preparation software for the purpose of preparing your tax return. This information includes your name, address, date of birth, phone number, SSN, filing status, occupation, employer&apos;s name and address, and the amounts and sources of income, deductions and credits that were  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ik4 {
            get {
                return ResourceManager.GetString("ik4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not need to provide consent for the VITA/TCE partner preparing your tax return this year. Global Carry Forward will assist you only if you visit a different VITA or TCE partner next year that uses TaxSlayer..
        /// </summary>
        public static string ik5 {
            get {
                return ResourceManager.GetString("ik5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation on the Duration of Consent: I/we, the taxpayer, do not wish to limit the duration of the consent of the disclosure of tax return information to a date earlier than presented above (November 12, 2022). If I/we wish to limit the duration of the consent of the disclosure to an earlier date, I/we will deny consent..
        /// </summary>
        public static string ik6 {
            get {
                return ResourceManager.GetString("ik6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation on the Scope of Disclosure: I/we, the taxpayer, do not wish to limit the scope of the disclosure of tax return information further than presented above. If I/we wish to limit the scope of the disclosure of tax return  information further than presented above, I/we will deny consent..
        /// </summary>
        public static string ik7 {
            get {
                return ResourceManager.GetString("ik7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income (or loss) from Rental Property?.
        /// </summary>
        public static string Income_or_loss_for_rental_property {
            get {
                return ResourceManager.GetString("Income_or_loss_for_rental_property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income (or loss) from the sale or exchange of Stocks, Bonds, Virtual Currency or Real Estate? (including your home) (Forms 1099-S,1099-B).
        /// </summary>
        public static string Income_or_oloss_from_the_sale {
            get {
                return ResourceManager.GetString("Income_or_oloss_from_the_sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake/Interview &amp; Quality Review Sheet.
        /// </summary>
        public static string Intake_Interview_QualityReviewSheet {
            get {
                return ResourceManager.GetString("Intake/Interview&QualityReviewSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake/Interview &amp; Quality Review Sheet.
        /// </summary>
        public static string Intakesheet {
            get {
                return ResourceManager.GetString("Intakesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest/Dividends from: checking/savings accounts, bonds, CDs, brokerage? (Forms 1099-INT, 1099-DIV).
        /// </summary>
        public static string Interest_dividents_from_checking {
            get {
                return ResourceManager.GetString("Interest_dividents_from_checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRA.
        /// </summary>
        public static string Ira {
            get {
                return ResourceManager.GetString("Ira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this person a qualifying child/relative of any other person? (yes/no).
        /// </summary>
        public static string Is_this_person_a_qualifying {
            get {
                return ResourceManager.GetString("Is_this_person_a_qualifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your spouse a U.S. citizen?.
        /// </summary>
        public static string Is_your_spouse_a_us_citizen {
            get {
                return ResourceManager.GetString("Is_your_spouse_a_us_citizen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.irs.gov.
        /// </summary>
        public static string kl10 {
            get {
                return ResourceManager.GetString("kl10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Number 52121E.
        /// </summary>
        public static string kl9 {
            get {
                return ResourceManager.GetString("kl9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name (Do not enter your name or spouse’s name).
        /// </summary>
        public static string Last_Name_Do_not_enter_your_name_or_spouses_name {
            get {
                return ResourceManager.GetString("Last_Name_Do_not_enter_your_name_or_spouses_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year, was your spouse:.
        /// </summary>
        public static string Last_year_was_your_spouse {
            get {
                return ResourceManager.GetString("Last_year_was_your_spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year, were you:.
        /// </summary>
        public static string Last_year_were_you {
            get {
                return ResourceManager.GetString("Last_year_were_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legally blind.
        /// </summary>
        public static string Legally_blind {
            get {
                return ResourceManager.GetString("Legally_blind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legally Separated.
        /// </summary>
        public static string Legally_speparated {
            get {
                return ResourceManager.GetString("Legally_speparated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List the names below of.
        /// </summary>
        public static string List_the_name_below_of {
            get {
                return ResourceManager.GetString("List_the_name_below_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.I..
        /// </summary>
        public static string M_I {
            get {
                return ResourceManager.GetString("M_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing address.
        /// </summary>
        public static string Mailing_address {
            get {
                return ResourceManager.GetString("Mailing_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make estimated tax payments or apply last year’s refund to this year’s tax? If so how much?.
        /// </summary>
        public static string Make_estimated_tax_payments {
            get {
                return ResourceManager.GetString("Make_estimated_tax_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        public static string married {
            get {
                return ResourceManager.GetString("married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical &amp; Dental (including insurance premiums).
        /// </summary>
        public static string Medical_and_dental_inculiding {
            get {
                return ResourceManager.GetString("Medical_and_dental_inculiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Interest (Form 1098).
        /// </summary>
        public static string Mortagage_interest {
            get {
                return ResourceManager.GetString("Mortagage_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name (Do not enter your name or spouse’s name).
        /// </summary>
        public static string Name_first_and_last_do_not_enter_your {
            get {
                return ResourceManager.GetString("Name_first_and_last_do_not_enter_your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEPHEW.
        /// </summary>
        public static string NEPHEW {
            get {
                return ResourceManager.GetString("NEPHEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NIECE.
        /// </summary>
        public static string NIECE {
            get {
                return ResourceManager.GetString("NIECE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of  months lived in your home  last year.
        /// </summary>
        public static string Number_of_months_lived_in_your_home {
            get {
                return ResourceManager.GetString("Number_of_months_lived_in_your_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Number 71414A.
        /// </summary>
        public static string ol5 {
            get {
                return ResourceManager.GetString("ol5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.irs.gov.
        /// </summary>
        public static string ol6 {
            get {
                return ResourceManager.GetString("ol6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15080 (EN-SP).
        /// </summary>
        public static string ol7 {
            get {
                return ResourceManager.GetString("ol7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Rev. 7-2020).
        /// </summary>
        public static string ol8 {
            get {
                return ResourceManager.GetString("ol8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OMB Number.
        /// </summary>
        public static string OMBNumber {
            get {
                return ResourceManager.GetString("OMBNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other income? (gambling, lottery, prizes, awards, jury duty, virtual currency, Sch K-1, royalties, foreign income, other property or services,.
        /// </summary>
        public static string Other_income_gamnling_lottery {
            get {
                return ResourceManager.GetString("Other_income_gamnling_lottery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PARENT.
        /// </summary>
        public static string PARENT {
            get {
                return ResourceManager.GetString("PARENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part I – Your Personal Information.
        /// </summary>
        public static string Part_first_your_personal_information {
            get {
                return ResourceManager.GetString("Part_first_your_personal_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part V – Life Events – Last Year, Did You (or Your Spouse).
        /// </summary>
        public static string Part_five_life_events {
            get {
                return ResourceManager.GetString("Part_five_life_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part IV – Expenses – Last Year, Did You (or Your Spouse) Pay.
        /// </summary>
        public static string Part_four_expenses {
            get {
                return ResourceManager.GetString("Part_four_expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part II – Marital Status and Household Information.
        /// </summary>
        public static string Part_second_marital_status_and_household_information {
            get {
                return ResourceManager.GetString("Part_second_marital_status_and_household_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part III – Income – Last Year, Did You (or Your Spouse) Receive.
        /// </summary>
        public static string Part_third_income_last_year_did_you {
            get {
                return ResourceManager.GetString("Part_third_income_last_year_did_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture ID (such as valid driver&apos;s license) for you and your spouse..
        /// </summary>
        public static string pictureidfor {
            get {
                return ResourceManager.GetString("pictureidfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete pages 1-4 of this form..
        /// </summary>
        public static string pleasecompt {
            get {
                return ResourceManager.GetString("pleasecompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presidential Election Campaign Fund (If you check a box, your tax or refund will not change).
        /// </summary>
        public static string Presidental_election_campaign_fund {
            get {
                return ResourceManager.GetString("Presidental_election_campaign_fund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary taxpayer printed name and signature.
        /// </summary>
        public static string Primary_signature {
            get {
                return ResourceManager.GetString("Primary_signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary taxpayer printed name.
        /// </summary>
        public static string Primary_taxpayer_printed_name {
            get {
                return ResourceManager.GetString("Primary_taxpayer_printed_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an email address (optional) (this email address will not be used for contacts from the Internal Revenue Service).
        /// </summary>
        public static string Provide_an_email_address {
            get {
                return ResourceManager.GetString("Provide_an_email_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase and install energy-efficient home items? (such as windows, furnace, insulation, etc.).
        /// </summary>
        public static string Purchase_and_install_energy_efficant {
            get {
                return ResourceManager.GetString("Purchase_and_install_energy_efficant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive an Economic Impact Payment (stimulus) in 2020?.
        /// </summary>
        public static string Receive_an_economic_impact_payment {
            get {
                return ResourceManager.GetString("Receive_an_economic_impact_payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive the First Time Homebuyers Credit in 2008?.
        /// </summary>
        public static string Recive_the_first_time_homebuyers {
            get {
                return ResourceManager.GetString("Recive_the_first_time_homebuyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund of state/local income taxes? (Form 1099-G).
        /// </summary>
        public static string Refund_of_state_local_income {
            get {
                return ResourceManager.GetString("Refund_of_state_local_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship to you.
        /// </summary>
        public static string Relationship_to_you_for_example {
            get {
                return ResourceManager.GetString("Relationship_to_you_for_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident of US, Canada, or Mexico last year (yes/no).
        /// </summary>
        public static string Resident_of_us_canada_or_maxico {
            get {
                return ResourceManager.GetString("Resident_of_us_canada_or_maxico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirement income or payments from Pensions. Annuities, and or IRA? (Form 1099-R).
        /// </summary>
        public static string Retriment_income_or_payments {
            get {
                return ResourceManager.GetString("Retriment_income_or_payments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not well.
        /// </summary>
        public static string rf10 {
            get {
                return ResourceManager.GetString("rf10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many free tax preparation sites operate by receiving grant money or other federal financial assistance. The data from the following questions may be used by this site to apply for these grants or to support continued receipt of financial funding . Your answer will be used only for statistical purposes. These questions are optional..
        /// </summary>
        public static string rf6 {
            get {
                return ResourceManager.GetString("rf6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you say you can carry on a conversation in English, both understanding &amp; speaking?.
        /// </summary>
        public static string rf7 {
            get {
                return ResourceManager.GetString("rf7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very well.
        /// </summary>
        public static string rf8 {
            get {
                return ResourceManager.GetString("rf8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well.
        /// </summary>
        public static string rf9 {
            get {
                return ResourceManager.GetString("rf9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roth IRA.
        /// </summary>
        public static string Roth_ira {
            get {
                return ResourceManager.GetString("Roth_ira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string sc10 {
            get {
                return ResourceManager.GetString("sc10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scholarships? (Forms W-2, 1098-T).
        /// </summary>
        public static string Scholarships_form_w_t {
            get {
                return ResourceManager.GetString("Scholarships_form_w_t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary taxpayer printed name and signature.
        /// </summary>
        public static string Secondry_signatue {
            get {
                return ResourceManager.GetString("Secondry_signatue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary taxpayer printed name.
        /// </summary>
        public static string Secondry_taxpayer_printed_name {
            get {
                return ResourceManager.GetString("Secondry_taxpayer_printed_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-Employment income? (Form 1099-MISC, 1099-NEC, cash, virtual currency, or other property or services).
        /// </summary>
        public static string Self_employment_income_form {
            get {
                return ResourceManager.GetString("Self_employment_income_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single or Married as of 12/31/20.
        /// </summary>
        public static string Single_or_married_as_of {
            get {
                return ResourceManager.GetString("Single_or_married_as_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SISTER.
        /// </summary>
        public static string SISTER {
            get {
                return ResourceManager.GetString("SISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number.
        /// </summary>
        public static string Social_security_number {
            get {
                return ResourceManager.GetString("Social_security_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security or Railroad Retirement Benefits? (Forms SSA-1099, RRB-1099).
        /// </summary>
        public static string Social_security_or_railroad_retirement {
            get {
                return ResourceManager.GetString("Social_security_or_railroad_retirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social security cards or ITIN letters for all persons on your tax return..
        /// </summary>
        public static string socialsecucard {
            get {
                return ResourceManager.GetString("socialsecucard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SON.
        /// </summary>
        public static string SON {
            get {
                return ResourceManager.GetString("SON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify.
        /// </summary>
        public static string Specify {
            get {
                return ResourceManager.GetString("Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEPBROTHER.
        /// </summary>
        public static string STEPBROTHER {
            get {
                return ResourceManager.GetString("STEPBROTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEPCHILD.
        /// </summary>
        public static string STEPCHILD {
            get {
                return ResourceManager.GetString("STEPCHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STEPSISTER.
        /// </summary>
        public static string STEPSISTER {
            get {
                return ResourceManager.GetString("STEPSISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student loan interest? (Form 1098-E).
        /// </summary>
        public static string Student_loan_interest {
            get {
                return ResourceManager.GetString("Student_loan_interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes (State, Real Estate, Personal Property, Sales).
        /// </summary>
        public static string Taxes_state_real_estate_personal {
            get {
                return ResourceManager.GetString("Taxes_state_real_estate_personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Information such as Forms W-2, 1099, 1098, 1095..
        /// </summary>
        public static string taxinfosuch {
            get {
                return ResourceManager.GetString("taxinfosuch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not at all.
        /// </summary>
        public static string tg1 {
            get {
                return ResourceManager.GetString("tg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Hawaiian or other Pacific Islander.
        /// </summary>
        public static string tg10 {
            get {
                return ResourceManager.GetString("tg10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer not to answer.
        /// </summary>
        public static string tg2 {
            get {
                return ResourceManager.GetString("tg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you say you can read a newspaper or book in English?.
        /// </summary>
        public static string tg3 {
            get {
                return ResourceManager.GetString("tg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you or any member of your household have a disability?.
        /// </summary>
        public static string tg4 {
            get {
                return ResourceManager.GetString("tg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you or your spouse a Veteran from the U.S. Armed Forces?.
        /// </summary>
        public static string tg5 {
            get {
                return ResourceManager.GetString("tg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your race?.
        /// </summary>
        public static string tg6 {
            get {
                return ResourceManager.GetString("tg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Indian or Alaska Native.
        /// </summary>
        public static string tg7 {
            get {
                return ResourceManager.GetString("tg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian.
        /// </summary>
        public static string tg8 {
            get {
                return ResourceManager.GetString("tg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black or African American.
        /// </summary>
        public static string tg9 {
            get {
                return ResourceManager.GetString("tg9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (This includes registered domestic partnerships, civil unions, or other formal relationships under state law).
        /// </summary>
        public static string This_includes_registered_domestic {
            get {
                return ResourceManager.GetString("This_includes_registered_domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip Income?.
        /// </summary>
        public static string Tip_income {
            get {
                return ResourceManager.GetString("Tip_income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be completed by a Certified Volunteer Preparer.
        /// </summary>
        public static string To_be_completed_by_a_certificate {
            get {
                return ResourceManager.GetString("To_be_completed_by_a_certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To purchase U.S. Savings Bonds.
        /// </summary>
        public static string To_purchase_us_savings_bonds {
            get {
                return ResourceManager.GetString("To_purchase_us_savings_bonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To split your refund between different accounts.
        /// </summary>
        public static string To_split_your_refund_between_diffrent {
            get {
                return ResourceManager.GetString("To_split_your_refund_between_diffrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally and permanently disabled.
        /// </summary>
        public static string Totally_and_permanently_disabled {
            get {
                return ResourceManager.GetString("Totally_and_permanently_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totally and Permanently Disabled.
        /// </summary>
        public static string Totally_and_permanently_disabled_yes_or_nos {
            get {
                return ResourceManager.GetString("Totally_and_permanently_disabled_yes_or_nos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Privacy Act of 1974 requires that when we ask for information we tell you our legal right to ask for the information, why we are asking for it, and how it will be used. We must also tell you what could happen if we do not receive it, and whether your response is voluntary, required to obtain a benefit, or mandatory. Our legal right to ask for information is 5 U.S.C. 301. We are asking for this information to assist us in contacting you relative to your interest and/or participation in the IRS volunteer  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string uj1 {
            get {
                return ResourceManager.GetString("uj1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal law requires this consent form be provided to you. Unless authorized by law, we cannot disclose your tax return information to third parties for purposes other than the preparation and filing of your tax return without your consent. If you consent to the disclosure of your tax return information, Federal law may not protect your tax return information from further use or distribution..
        /// </summary>
        public static string uj10 {
            get {
                return ResourceManager.GetString("uj10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Number 52121E.
        /// </summary>
        public static string uj2 {
            get {
                return ResourceManager.GetString("uj2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.irs.gov.
        /// </summary>
        public static string uj3 {
            get {
                return ResourceManager.GetString("uj3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form 13614-C (Rev. 10-2020).
        /// </summary>
        public static string uj4 {
            get {
                return ResourceManager.GetString("uj4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15080 (EN-SP).
        /// </summary>
        public static string uj5 {
            get {
                return ResourceManager.GetString("uj5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (July 2020).
        /// </summary>
        public static string uj6 {
            get {
                return ResourceManager.GetString("uj6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of the Treasury - Internal Revenue Service.
        /// </summary>
        public static string uj7 {
            get {
                return ResourceManager.GetString("uj7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent to Disclose Tax Return Information to VITA/TCE Tax Preparation Sites.
        /// </summary>
        public static string uj8 {
            get {
                return ResourceManager.GetString("uj8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Disclosure:.
        /// </summary>
        public static string uj9 {
            get {
                return ResourceManager.GetString("uj9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNCLE.
        /// </summary>
        public static string UNCLE {
            get {
                return ResourceManager.GetString("UNCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unemployment Compensation? (Form 1099G).
        /// </summary>
        public static string Unemployment_compensation {
            get {
                return ResourceManager.GetString("Unemployment_compensation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsure.
        /// </summary>
        public static string Unsure {
            get {
                return ResourceManager.GetString("Unsure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your Documents here:.
        /// </summary>
        public static string Upload_your_documents_here {
            get {
                return ResourceManager.GetString("Upload_your_documents_here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Files:.
        /// </summary>
        public static string Uploaded_files {
            get {
                return ResourceManager.GetString("Uploaded_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to US  Citizen.
        /// </summary>
        public static string Us_citizen_tes_or_no {
            get {
                return ResourceManager.GetString("Us_citizen_tes_or_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wages or Salary? (Form W-2).
        /// </summary>
        public static string Wages_or_salary_form_w {
            get {
                return ResourceManager.GetString("Wages_or_salary_form_w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to who lived with you last year (other than your spouse).
        /// </summary>
        public static string Who_lived_with_you_last_year {
            get {
                return ResourceManager.GetString("Who_lived_with_you_last_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widowed.
        /// </summary>
        public static string Widowed {
            get {
                return ResourceManager.GetString("Widowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of spouse’s death.
        /// </summary>
        public static string Year_of_spouse_deaths {
            get {
                return ResourceManager.GetString("Year_of_spouse_deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string yh1 {
            get {
                return ResourceManager.GetString("yh1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Act and Paperwork Reduction Act Notice.
        /// </summary>
        public static string yh10 {
            get {
                return ResourceManager.GetString("yh10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spouse’s race?.
        /// </summary>
        public static string yh2 {
            get {
                return ResourceManager.GetString("yh2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Indian or Alaska Native.
        /// </summary>
        public static string yh3 {
            get {
                return ResourceManager.GetString("yh3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Hawaiian or other Pacific Islander.
        /// </summary>
        public static string yh4 {
            get {
                return ResourceManager.GetString("yh4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spouse.
        /// </summary>
        public static string yh5 {
            get {
                return ResourceManager.GetString("yh5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ethnicity?.
        /// </summary>
        public static string yh6 {
            get {
                return ResourceManager.GetString("yh6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hispanic or Latino.
        /// </summary>
        public static string yh7 {
            get {
                return ResourceManager.GetString("yh7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Hispanic or Latino.
        /// </summary>
        public static string yh8 {
            get {
                return ResourceManager.GetString("yh8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comments.
        /// </summary>
        public static string yh9 {
            get {
                return ResourceManager.GetString("yh9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you supported but did not live with you last year.
        /// </summary>
        public static string You_support_but_did_not_live_with_you {
            get {
                return ResourceManager.GetString("You_support_but_did_not_live_with_you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are responsible for the information on your return. Please provide
        ///complete and accurate information..
        /// </summary>
        public static string youareresponsi {
            get {
                return ResourceManager.GetString("youareresponsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Date of Birth.
        /// </summary>
        public static string Your_date_of_birth {
            get {
                return ResourceManager.GetString("Your_date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your first name.
        /// </summary>
        public static string Your_first_name {
            get {
                return ResourceManager.GetString("Your_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your job title.
        /// </summary>
        public static string Your_job_title {
            get {
                return ResourceManager.GetString("Your_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spouse’s Date of Birth.
        /// </summary>
        public static string Your_spouse_date_of_birth {
            get {
                return ResourceManager.GetString("Your_spouse_date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spouse’s first name.
        /// </summary>
        public static string Your_spouse_first_name {
            get {
                return ResourceManager.GetString("Your_spouse_first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your spouse’s job title.
        /// </summary>
        public static string Your_spouse_job_title {
            get {
                return ResourceManager.GetString("Your_spouse_job_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need:.
        /// </summary>
        public static string Youwillbe {
            get {
                return ResourceManager.GetString("Youwillbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP Code.
        /// </summary>
        public static string Zip_code {
            get {
                return ResourceManager.GetString("Zip_code", resourceCulture);
            }
        }
    }
}
